# Generated by Django 4.1.1 on 2023-06-02 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='company_profile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='Summary',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='about_us',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='contact_us',
            field=models.TextField(null=True),
        ),
    ]
