# Generated by Django 4.1.1 on 2023-06-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_information_company_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(null=True),
        ),
    ]
