# Generated by Django 4.1.1 on 2023-06-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_projects_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
