# Generated by Django 4.1.1 on 2023-06-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='rating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
