# Generated by Django 4.1.1 on 2023-06-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_skills_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
